from __future__ import annotations

import hashlib
import json
import os
import re
import shlex
import subprocess
from pathlib import Path

import pytest

from cc_swaper.profiles import ProfileStore
from cc_swaper.shell import _managed_block, _source_script, install, installed, uninstall


def _trusted_binaries(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> tuple[Path, Path]:
    fake_bin = tmp_path / "trusted bin"
    fake_bin.mkdir()
    fake_ccs = fake_bin / "ccs"
    fake_ccs.write_text(
        "#!/usr/bin/env python3\n"
        "import json, os, sys\n"
        "with open(os.environ['CCS_LOG'], 'a') as h: h.write(json.dumps(sys.argv[1:]) + '\\n')\n"
        "with open(os.environ['CCS_BIN_LOG'], 'a') as h: h.write(os.environ.get('CC_SWAPER_CLAUDE_BIN', '') + '\\n')\n"
    )
    fake_ccs.chmod(0o755)
    fake_claude = fake_bin / "claude"
    fake_claude.write_text("#!/bin/sh\nexit 0\n")
    fake_claude.chmod(0o755)
    monkeypatch.setenv("PATH", f"{fake_bin}{os.pathsep}{os.environ['PATH']}")
    return fake_ccs.resolve(), fake_claude.resolve()


def _v060_source_script(ccs_path: Path, claude_path: Path) -> str:
    """Return the exact generated wrapper from the v0.6.0 release."""
    template = """# Generated by cc-swaper. Use `ccs shell uninstall` to remove.
# This function affects interactive Zsh only; scripts keep the native binary.
function claude() {
  local first="${1-}"
  local arg
  local -x CC_SWAPER_CLAUDE_BIN=__CLAUDE_BIN__
  case "$first" in
    auth|agents|attach|config|doctor|gateway|import|install|kill|logs|mcp|plugin|plugins|project|respawn|rm|setup-token|stop|ultrareview|update|upgrade)
      command __CCS_BIN__ native -- "$@"
      return $?
      ;;
  esac
  if [[ "$first" == "-c" || "$first" == "--continue" ]] && [[ $# -eq 1 ]]; then
    command __CCS_BIN__ resume
    return $?
  fi
  if [[ "$first" == "-r" || "$first" == "--resume" ]] && [[ $# -eq 2 ]]; then
    command __CCS_BIN__ resume "$2"
    return $?
  fi
  for arg in "$@"; do
    case "$arg" in
      -p|--print|--bg|--background|-c|--continue|-r|--resume|--help|-h|-v|--version)
        command __CCS_BIN__ native -- "$@"
        return $?
        ;;
    esac
  done
  command __CCS_BIN__ run -- "$@"
}
"""
    quoted = {
        "__CCS_BIN__": shlex.quote(str(ccs_path)),
        "__CLAUDE_BIN__": shlex.quote(str(claude_path)),
    }
    return re.sub(r"__CCS_BIN__|__CLAUDE_BIN__", lambda match: quoted[match.group()], template)


def test_shell_install_is_reversible_and_idempotent(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    ccs_path, claude_path = _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    original = "export EXAMPLE=1\n"
    rc.write_text(original)
    rc.chmod(0o600)
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")

    assert install(store) == rc
    assert installed(store)
    first = rc.read_text()
    assert "source " in first
    script = store.home / "claude.zsh"
    assert script.read_text() == _source_script(ccs_path, claude_path)
    assert 'command ' + shlex.quote(str(ccs_path)) + ' native -- "$@"' in script.read_text()
    assert install(store) == rc
    assert rc.read_text() == first
    assert (store.home / "claude.zsh").stat().st_mode & 0o777 == 0o600

    assert uninstall(store) == rc
    assert rc.read_text() == original
    assert not (store.home / "claude.zsh").exists()
    assert not installed(store)


def test_shell_wrapper_forwards_all_arguments_and_pins_claude_binary(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    fake_ccs, fake_claude = _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")

    install(store)
    log = tmp_path / "calls.jsonl"
    bin_log = tmp_path / "claude-bins.txt"
    env = dict(os.environ)
    env.update({
        "ZDOTDIR": str(zdotdir),
        "CCS_LOG": str(log),
        "CCS_BIN_LOG": str(bin_log),
        "PATH": os.environ["PATH"],
    })
    result = subprocess.run(
        [
            "zsh", "-ic",
            "claude 'fix bug' --model 'sonnet 4' ''; claude auth status; "
            "claude -c; claude --print hi; claude --version; claude",
        ],
        env=env, capture_output=True, text=True, timeout=10,
    )
    assert result.returncode == 0, result.stderr
    calls = [json.loads(line) for line in log.read_text().splitlines()]
    assert calls == [
        ["native", "--", "fix bug", "--model", "sonnet 4", ""],
        ["native", "--", "auth", "status"],
        ["native", "--", "-c"],
        ["native", "--", "--print", "hi"],
        ["native", "--", "--version"],
        ["native", "--"],
    ]
    assert bin_log.read_text().splitlines() == [str(fake_claude)] * len(calls)
    script = (store.home / "claude.zsh").read_text()
    assert f"local -x CC_SWAPER_CLAUDE_BIN={shlex.quote(str(fake_claude))}" in script
    assert " native -- \"$@\"" in script
    assert " run -- " not in script
    assert " resume" not in script


def test_shell_install_refuses_existing_claude_alias(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    original = "alias claude='other-wrapper'\n"
    rc.write_text(original)
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")

    with pytest.raises(RuntimeError, match="existing claude alias"):
        install(store)
    assert rc.read_text() == original
    assert not (store.home / "claude.zsh").exists()


def test_shell_uninstall_preserves_rc_without_trailing_newline(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    original = "export EXAMPLE=1"
    rc.write_text(original)
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")

    install(store)
    uninstall(store)
    assert rc.read_text() == original


def test_shell_uninstall_preserves_modified_generated_script(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")
    install(store)
    script = store.home / "claude.zsh"
    script.write_text(script.read_text() + "# my addition\n")

    uninstall(store)
    assert script.is_file()
    assert not installed(store)


def test_shell_uninstall_rejects_tampered_source_block(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")
    rc = install(store)
    current = rc.read_text()
    tampered = current.replace(str(store.home / "claude.zsh"), "/tmp/other-script")
    rc.write_text(tampered)

    with pytest.raises(RuntimeError, match="expected script"):
        uninstall(store)
    assert rc.read_text() == tampered


def test_shell_install_rejects_writable_zshrc(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    rc.write_text("# user config\n")
    rc.chmod(0o666)
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")

    with pytest.raises(RuntimeError, match="writable by others"):
        install(store)


def test_shell_store_change_refuses_to_modify_existing_integration(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    old_store = ProfileStore(tmp_path / "old-store")
    new_store = ProfileStore(tmp_path / "new-store")
    rc = install(old_store)
    original = rc.read_text()

    with pytest.raises(RuntimeError, match="expected script"):
        install(new_store)
    with pytest.raises(RuntimeError, match="expected script"):
        uninstall(new_store)
    assert rc.read_text() == original
    assert installed(old_store)
    uninstall(old_store)


def test_shell_install_upgrades_valid_v060_wrapper_in_place(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    ccs_path, claude_path = _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")
    script = store.home / "claude.zsh"
    old_contents = _v060_source_script(ccs_path, claude_path)
    script.write_text(old_contents)
    script.chmod(0o600)
    prefix = "export BEFORE=1\n"
    suffix = "\nexport AFTER=1\n"
    old_digest = hashlib.sha256(old_contents.encode()).hexdigest()
    rc.write_text(prefix + _managed_block(script, "yes", old_digest) + suffix)
    rc.chmod(0o600)

    assert installed(store)
    install(store)

    new_contents = _source_script(ccs_path, claude_path)
    new_digest = hashlib.sha256(new_contents.encode()).hexdigest()
    assert script.read_text() == new_contents
    assert rc.read_text() == prefix + _managed_block(script, "yes", new_digest) + suffix
    assert installed(store)
    uninstall(store)
    assert rc.read_text() == prefix + suffix[1:]
    assert not script.exists()


def test_shell_install_recovers_interrupted_wrapper_upgrade(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    ccs_path, claude_path = _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")
    script = store.home / "claude.zsh"
    old_contents = _v060_source_script(ccs_path, claude_path)
    old_digest = hashlib.sha256(old_contents.encode()).hexdigest()
    rc.write_text(_managed_block(script, "no", old_digest) + "\n")
    rc.chmod(0o600)
    # State left behind if the process exited between the two atomic writes.
    new_contents = _source_script(ccs_path, claude_path)
    script.write_text(new_contents)
    script.chmod(0o600)

    install(store)

    assert installed(store)
    assert script.read_text() == new_contents
    assert hashlib.sha256(new_contents.encode()).hexdigest() in rc.read_text()


def test_shell_install_refuses_tampered_managed_script_during_upgrade(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    ccs_path, claude_path = _trusted_binaries(tmp_path, monkeypatch)
    zdotdir = tmp_path / "zsh"
    zdotdir.mkdir()
    rc = zdotdir / ".zshrc"
    monkeypatch.setenv("ZDOTDIR", str(zdotdir))
    store = ProfileStore(tmp_path / "store")
    script = store.home / "claude.zsh"
    old_contents = _v060_source_script(ccs_path, claude_path)
    old_digest = hashlib.sha256(old_contents.encode()).hexdigest()
    script.write_text(old_contents)
    script.chmod(0o600)
    original_rc = (
        "export USER_SETTING=kept\n"
        + _managed_block(script, "yes", old_digest)
        + "\n# after managed block\n"
    )
    rc.write_text(original_rc)
    rc.chmod(0o600)
    tampered = old_contents + "# local edit\n"
    script.write_text(tampered)

    with pytest.raises(RuntimeError, match="script was modified"):
        install(store)
    assert rc.read_text() == original_rc
    assert script.read_text() == tampered


def test_source_script_does_not_resubstitute_marker_inside_quoted_path(tmp_path: Path) -> None:
    binary_dir = tmp_path / "c c" / "__CLAUDE_BIN__"
    binary_dir.mkdir(parents=True)
    fake_ccs = binary_dir / "ccs"
    fake_ccs.write_text(
        "#!/bin/sh\n"
        "printf '%s\\n' \"$CC_SWAPER_CLAUDE_BIN\" > \"$CCS_LOG\"\n"
    )
    fake_ccs.chmod(0o755)
    suspicious_claude = tmp_path / "claude; echo INJECTED"
    wrapper = tmp_path / "wrapper.zsh"
    wrapper.write_text(_source_script(fake_ccs, suspicious_claude))
    log = tmp_path / "seen-path"
    env = dict(os.environ, CCS_LOG=str(log))

    result = subprocess.run(
        ["zsh", "-f", "-c", f"source {shlex.quote(str(wrapper))}; claude hello"],
        env=env, capture_output=True, text=True, timeout=5,
    )
    assert result.returncode == 0, result.stderr
    assert log.read_text().strip() == str(suspicious_claude)
    assert "INJECTED" not in result.stdout + result.stderr
