"""Reversible Zsh integration for interactive `claude` commands."""

from __future__ import annotations

import os
import hashlib
import re
import shlex
import shutil
import stat
import tempfile
from pathlib import Path

from .profiles import ProfileStore


START = "# >>> cc-swaper shell >>>"
END = "# <<< cc-swaper shell <<<"


def _zshrc() -> Path:
    root = Path(os.environ.get("ZDOTDIR") or Path.home()).expanduser()
    return root / ".zshrc"


def _atomic_text(path: Path, content: str, mode: int) -> None:
    fd, raw_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(raw_name)
    try:
        os.fchmod(fd, mode)
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_path, path)
    finally:
        if temp_path.exists():
            temp_path.unlink()


def _trusted_ccs_path() -> Path:
    raw = shutil.which("ccs")
    if not raw or not Path(raw).is_absolute():
        raise RuntimeError("ccs must be installed on an absolute PATH entry")
    path = Path(raw)
    target = path.resolve(strict=True)
    for candidate in (path.parent, target.parent):
        info = candidate.stat()
        if info.st_uid not in (0, os.getuid()) or stat.S_IMODE(info.st_mode) & 0o022:
            raise RuntimeError(f"ccs executable directory is writable by others: {candidate}")
    info = target.stat()
    if not stat.S_ISREG(info.st_mode) or info.st_uid not in (0, os.getuid()):
        raise RuntimeError(f"untrusted ccs executable: {target}")
    if stat.S_IMODE(info.st_mode) & 0o022:
        raise RuntimeError(f"ccs executable is writable by others: {target}")
    if not os.access(target, os.X_OK):
        raise RuntimeError(f"ccs executable is not executable: {target}")
    return target


def _trusted_claude_path() -> Path:
    raw = shutil.which("claude")
    if not raw or not Path(raw).is_absolute():
        raise RuntimeError("Claude Code must be installed on an absolute PATH entry")
    path = Path(raw)
    target = path.resolve(strict=True)
    for candidate in (path.parent, target.parent):
        info = candidate.stat()
        if info.st_uid not in (0, os.getuid()) or stat.S_IMODE(info.st_mode) & 0o022:
            raise RuntimeError(f"Claude Code executable directory is writable by others: {candidate}")
    info = target.stat()
    if not stat.S_ISREG(info.st_mode) or info.st_uid not in (0, os.getuid()):
        raise RuntimeError(f"untrusted Claude Code executable: {target}")
    if stat.S_IMODE(info.st_mode) & 0o022 or not os.access(target, os.X_OK):
        raise RuntimeError(f"Claude Code executable is not private/executable: {target}")
    return target


def _source_script(ccs_path: Path, claude_path: Path) -> str:
    template = """# Generated by cc-swaper. Use `ccs shell uninstall` to remove.
# This function affects interactive Zsh only; scripts keep the native binary.
function claude() {
  local first="${1-}"
  local arg
  local -x CC_SWAPER_CLAUDE_BIN=__CLAUDE_BIN__
  case "$first" in
    auth|agents|attach|config|doctor|gateway|import|install|kill|logs|mcp|plugin|plugins|project|respawn|rm|setup-token|stop|ultrareview|update|upgrade)
      command __CCS_BIN__ native -- "$@"
      return $?
      ;;
  esac
  if [[ "$first" == "-c" || "$first" == "--continue" ]] && [[ $# -eq 1 ]]; then
    command __CCS_BIN__ resume
    return $?
  fi
  if [[ "$first" == "-r" || "$first" == "--resume" ]] && [[ $# -eq 2 ]]; then
    command __CCS_BIN__ resume "$2"
    return $?
  fi
  for arg in "$@"; do
    case "$arg" in
      -p|--print|--bg|--background|-c|--continue|-r|--resume|--help|-h|-v|--version)
        command __CCS_BIN__ native -- "$@"
        return $?
        ;;
    esac
  done
  command __CCS_BIN__ run -- "$@"
}
"""
    quoted = {
        "__CCS_BIN__": shlex.quote(str(ccs_path)),
        "__CLAUDE_BIN__": shlex.quote(str(claude_path)),
    }
    # Substitute against the original template in one pass. A quoted path may
    # itself contain the other marker; replacements must never be rescanned.
    return re.sub(r"__CCS_BIN__|__CLAUDE_BIN__", lambda match: quoted[match.group()], template)


def _read_rc(path: Path) -> tuple[str, int]:
    parent = path.parent
    if parent.is_symlink():
        raise RuntimeError(f"refusing symlinked Zsh config directory: {parent}")
    parent_info = parent.stat()
    if parent_info.st_uid not in (0, os.getuid()) or stat.S_IMODE(parent_info.st_mode) & 0o022:
        raise RuntimeError(f"Zsh config directory is writable by others: {parent}")
    if path.is_symlink():
        raise RuntimeError(f"refusing to edit symlinked Zsh config: {path}")
    if not path.exists():
        return "", 0o600
    info = path.stat()
    if not stat.S_ISREG(info.st_mode) or info.st_uid != os.getuid():
        raise RuntimeError(f"Zsh config is not a regular file owned by you: {path}")
    if stat.S_IMODE(info.st_mode) & 0o022:
        raise RuntimeError(f"Zsh config is writable by others: {path}")
    return path.read_text(encoding="utf-8"), stat.S_IMODE(info.st_mode)


def _managed_block(script: Path, trailing: str, digest: str) -> str:
    quoted = shlex.quote(str(script))
    return (
        f"{START}\n# cc-swaper-original-trailing-newline: {trailing}\n"
        f"# cc-swaper-script-sha256: {digest}\n"
        f"[[ -r {quoted} ]] && source {quoted}\n{END}"
    )


def _split_managed_block(current: str, script: Path) -> tuple[str, str, str, str] | None:
    if START not in current and END not in current:
        return None
    if current.count(START) != 1 or current.count(END) != 1:
        raise RuntimeError("ambiguous cc-swaper block in Zsh config")
    start = current.index(START)
    end = current.index(END) + len(END)
    managed = current[start:end]
    lines = managed.splitlines()
    if len(lines) != 5 or lines[0] != START or lines[4] != END:
        raise RuntimeError("modified cc-swaper block in Zsh config")
    trailing_match = re.fullmatch(r"# cc-swaper-original-trailing-newline: (yes|no)", lines[1])
    digest_match = re.fullmatch(r"# cc-swaper-script-sha256: ([0-9a-f]{64})", lines[2])
    if not trailing_match or not digest_match:
        raise RuntimeError("modified cc-swaper block in Zsh config")
    trailing, digest = trailing_match.group(1), digest_match.group(1)
    if managed != _managed_block(script, trailing, digest):
        raise RuntimeError("cc-swaper block does not source the expected script")
    return current[:start], current[end:], trailing, digest


def install(store: ProfileStore) -> Path:
    rc = _zshrc()
    current, mode = _read_rc(rc)
    script = store.home / "claude.zsh"
    existing_block = _split_managed_block(current, script)
    if existing_block is None and (
        re.search(r"(?m)^\s*alias\s+claude=", current)
        or re.search(r"(?m)^\s*(?:function\s+claude\b|claude\s*\(\))", current)
    ):
        raise RuntimeError("an existing claude alias/function is present in Zsh config")
    if script.is_symlink():
        raise RuntimeError(f"refusing symlinked shell integration: {script}")
    if existing_block is not None:
        if not script.is_file():
            raise RuntimeError(f"shell integration script is missing: {script}")
        digest = hashlib.sha256(script.read_bytes()).hexdigest()
        if digest != existing_block[3]:
            raise RuntimeError(f"shell integration script was modified: {script}")
        return rc
    if script.exists():
        raise RuntimeError(f"shell integration path already exists: {script}")
    contents = _source_script(_trusted_ccs_path(), _trusted_claude_path())
    digest = hashlib.sha256(contents.encode()).hexdigest()
    _atomic_text(script, contents, 0o600)
    trailing = "yes" if current.endswith("\n") else "no"
    block = _managed_block(script, trailing, digest) + "\n"
    updated = current + ("" if not current or current.endswith("\n") else "\n") + block
    _atomic_text(rc, updated, mode)
    return rc


def uninstall(store: ProfileStore) -> Path:
    rc = _zshrc()
    current, mode = _read_rc(rc)
    script = store.home / "claude.zsh"
    existing_block = _split_managed_block(current, script)
    if existing_block is not None:
        before, after, trailing, digest = existing_block
        if trailing == "no" and before.endswith("\n"):
            before = before[:-1]
        updated = before + (after[1:] if after.startswith("\n") else after)
        _atomic_text(rc, updated, mode)
    if existing_block is not None and script.is_file() and not script.is_symlink():
        if hashlib.sha256(script.read_bytes()).hexdigest() == digest:
            script.unlink()
    return rc


def installed(store: ProfileStore) -> bool:
    rc = _zshrc()
    if not rc.is_file() or rc.is_symlink():
        return False
    script = store.home / "claude.zsh"
    try:
        block = _split_managed_block(rc.read_text(encoding="utf-8"), script)
    except RuntimeError:
        return False
    if block is None or not script.is_file() or script.is_symlink():
        return False
    return hashlib.sha256(script.read_bytes()).hexdigest() == block[3]
